server:
    servlet:
        context-path: ${BASE_URL:/}
    port: ${PORT:3600}

spring:
    application:
        name: singlarr
    thymeleaf:
        cache: false
    flyway:
        baseline-on-migrate: true
    datasource:
        url: "jdbc:sqlite:${app.path.config}/singlarr.db"
        driver-class-name: org.sqlite.JDBC
    jpa:
        database-platform: "org.hibernate.community.dialect.SQLiteDialect"
    security:
        user:
            name: ${USER:admin}
            password: ${PASSWORD:admin}

logging:
    level:
        root: ${LOGGING_LEVEL:INFO}

app:
    path:
        config: "${CONFIG_PATH:/config}"
        download: "${DOWNLOAD_PATH:/downloads}"
        library: "${LIBRARY_PATH:/library}"
    encryption:
        key: ${ENCRYPTION_KEY:}
    user-agent: ${USER_AGENT:Singlarr/1.0}

disable-security: ${DISABLE_SECURITY:${USER:true}}
